version: "3"
services:
  datascience-rstudio:
    image: bowenwen/rstudio:latest
    volumes:
      - $pwd:/home/rstudio
    restart: always
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=test
      - ROOT=TRUE
    container_name: dockerrstudio
    command: /init
    
