version: '2'
services:
    postgresql:
      image: postgres:latest
      container_name: "gogs-postgresql"
      restart: always
      volumes:
        - "./data/postgresql:/var/lib/postgresql"
      environment:
        - "POSTGRES_USER=gogs"
        - "POSTGRES_PASSWORD=translink"
        - "POSTGRES_DB=gogs"
      ports:
        - "5432:5432"
    gogs:
      image: gogs/gogs:latest
      container_name: "gogs"
      restart: always
      ports:
        - "10022:22"
        - "10080:3000"
      volumes:
        - "./data/gogs:/data"
      #  - "./entrypoint.sh:/entrypoint.sh"
      links:
        - postgresql
      #entrypoint: "/entrypoint.sh"

#https://github.com/hui000444/gogs-postgresql-docker-compose/blob/master/docker-compose.yml
